# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LoIu_ibhKAb_e112sUocqvzVYWiLCDZJ
"""

import torch
print('CUDA available:', torch.cuda.is_available())
print('Device:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU only — enable GPU!')

!pip uninstall -y torchvision

# Core TTS framework + audio utils, with a transformers version coqui-tts can use
!pip install -q coqui-tts librosa soundfile pandas "transformers==4.53.0"
print('Installed. Now: Runtime -> Restart session, then run from the download cell.')

import os, requests, tarfile, zipfile, glob

REPO = 'pnfo/sinhala-tts-dataset'   # repo moved from 'pathnirvana/...'
TAG  = 'v2.1'                        # latest "13.8 hours dataset"
ROOT = '/content/pathnirvana'
os.makedirs(ROOT, exist_ok=True)

# --- metadata (small) ---
if not os.path.exists(f'{ROOT}/metadata.csv'):
    !wget -q https://raw.githubusercontent.com/{REPO}/{TAG}/metadata.csv -O {ROOT}/metadata.csv
print('metadata rows:', sum(1 for _ in open(f'{ROOT}/metadata.csv', encoding='utf-8')))

# --- find the wav archive in the v2.1 release (it's the largest asset) ---
WAVS_DIR = f'{ROOT}/wavs'
if not glob.glob(f'{WAVS_DIR}/sinh_*.wav'):
    rel = requests.get(
        f'https://api.github.com/repos/{REPO}/releases/tags/{TAG}',
        headers={'Accept': 'application/vnd.github+json'}
    ).json()
    assets = rel.get('assets', [])
    print('Assets found:')
    for a in assets:
        print('  ', a['name'], '—', a['size'] // 1024 // 1024, 'MB')
    assert assets, 'No assets returned (rate-limited?). Re-run in a minute.'

    archive = max(assets, key=lambda a: a['size'])   # wav tarball = biggest asset
    url, name = archive['browser_download_url'], archive['name']
    print('Downloading', name, '...')
    !wget -q "{url}" -O /content/wavs_archive

    # auto-detect zip vs tar(.gz/.xz/.bz2)
    if zipfile.is_zipfile('/content/wavs_archive'):
        with zipfile.ZipFile('/content/wavs_archive') as z: z.extractall(ROOT)
    else:
        with tarfile.open('/content/wavs_archive') as t: t.extractall(ROOT)

# locate the folder that actually holds the new sinh_*.wav files
cands = [d for d, _, fs in os.walk(ROOT)
         if any(f.startswith('sinh_') and f.endswith('.wav') for f in fs)]
WAVS_DIR = cands[0] if cands else WAVS_DIR
print('WAV folder:', WAVS_DIR, '| sinh_ wavs:', len(glob.glob(f'{WAVS_DIR}/sinh_*.wav')))

import pandas as pd, os, glob, random
random.seed(1234)

SPEAKER   = 'mettananda'   # 'mettananda' (male, ~5400 clips) or 'oshadi' (female, ~985)
TEXT_MODE = 'sinhala'      # 'sinhala' or 'roman'

# metadata.csv: file_id | romanized | sinhala | speaker  (pipe-delimited, no header)
rows = []
with open(f'{ROOT}/metadata.csv', encoding='utf-8') as f:
    for line in f:
        p = line.rstrip('\n').split('|')
        if len(p) == 4:
            rows.append(p)
df = pd.DataFrame(rows, columns=['id', 'roman', 'sinhala', 'speaker'])
df = df[df.speaker == SPEAKER].copy()

def clean(t):
    t = t.strip()
    t = t.replace('-පෙ-', '').strip()   # drop the '-පෙ-' repetition marker
    return ' '.join(t.split())

col = 'sinhala' if TEXT_MODE == 'sinhala' else 'roman'
df['text'] = df[col].map(clean)

# keep only rows whose wav actually exists
df['wav'] = df.id.map(lambda i: os.path.join(WAVS_DIR, i + '.wav'))
df = df[df.wav.map(os.path.exists) & (df.text.str.len() > 0)].reset_index(drop=True)
print('usable clips:', len(df))

# Coqui ljspeech formatter expects:  <id>|<text>|<normalized_text>  and wavs/<id>.wav
DATA = '/content/si_tts'
os.makedirs(f'{DATA}/wavs', exist_ok=True)
for _, r in df.iterrows():
    dst = f"{DATA}/wavs/{r.id}.wav"
    if not os.path.exists(dst):
        os.symlink(r.wav, dst)

# train / eval split
idx = list(range(len(df))); random.shuffle(idx)
n_eval = max(50, int(0.02 * len(df)))
eval_idx = set(idx[:n_eval])

def write(path, keep):
    with open(path, 'w', encoding='utf-8') as f:
        for i, r in df.iterrows():
            if (i in eval_idx) == keep:
                f.write(f'{r.id}|{r.text}|{r.text}\n')

write(f'{DATA}/metadata_train.csv', keep=False)
write(f'{DATA}/metadata_eval.csv',  keep=True)
print('train:', len(df) - n_eval, '| eval:', n_eval)

# vocabulary (for the character-based model)
vocab = sorted(set(''.join(df.text)))
print('unique characters:', len(vocab))

import os
from trainer import Trainer, TrainerArgs
from TTS.tts.configs.shared_configs import BaseDatasetConfig, CharactersConfig
from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.vits import Vits, VitsAudioConfig
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor

# -------- torchaudio.info fallback patch (harmless if unused) --------
import torchaudio
from TTS.tts.datasets import dataset
def patched_get_audio_size(audiopath):
    try:
        return torchaudio.info(audiopath).num_frames
    except Exception:
        import librosa
        y, sr = librosa.load(audiopath, sr=None)
        return len(y)
dataset.get_audio_size = patched_get_audio_size
# ---------------------------------------------------------------------

DATA = '/content/si_tts'
OUT  = '/content/vits_si_out'
os.makedirs(OUT, exist_ok=True)
assert os.path.exists(f'{DATA}/metadata_train.csv'), \
    f'{DATA}/metadata_train.csv not found — run the preprocess cell first.'
print('DATA:', DATA, '| OUT:', OUT)

train_ds = BaseDatasetConfig(formatter='ljspeech', meta_file_train='metadata_train.csv', path=DATA)
eval_ds  = BaseDatasetConfig(formatter='ljspeech', meta_file_train='metadata_eval.csv',  path=DATA)

audio = VitsAudioConfig(sample_rate=22050, win_length=1024, hop_length=256,
                        num_mels=80, mel_fmin=0, mel_fmax=None)

# --- vocab from the metadata file (restart-proof; no df dependency) ---
punctuation_str = "!'(),-.:;?‘’“” "
texts = []
with open(f'{DATA}/metadata_train.csv', encoding='utf-8') as f:
    for line in f:
        parts = line.rstrip('\n').split('|')
        if len(parts) >= 2:
            texts.append(parts[1])                 # column 1 = text
letter_chars = ''.join(sorted(set(''.join(texts)) - set(punctuation_str)))
print('chars:', len(letter_chars), '| sample:', letter_chars[:30])

chars_config = CharactersConfig(
    characters_class='TTS.tts.utils.text.characters.Graphemes',
    pad='<PAD>', eos='<EOS>', bos='<BOS>', blank='<BLNK>',
    characters=letter_chars,
    punctuations=punctuation_str,
)

config = VitsConfig(
    audio=audio,
    run_name='vits_sinhala',
    batch_size=16,
    eval_batch_size=8,
    num_loader_workers=2,
    num_eval_loader_workers=2,
    run_eval=True,
    test_delay_epochs=5,
    epochs=50,
    use_phonemes=False,
    characters=chars_config,
    text_cleaner='multilingual_cleaners',
    print_step=50,
    save_step=1000,
    save_n_checkpoints=3,
    mixed_precision=True,
    output_path=OUT,
    datasets=[train_ds],
    test_sentences=[
        'අද දිනය හොඳ දිනයකි.',
        'ශ්‍රී ලංකාව ලස්සන රටකි.',
    ],
)

ap = AudioProcessor.init_from_config(config)
tokenizer, config = TTSTokenizer.init_from_config(config)

train_samples, _ = load_tts_samples(train_ds, eval_split=False)
eval_samples,  _ = load_tts_samples(eval_ds,  eval_split=False)
print('train samples:', len(train_samples), '| eval samples:', len(eval_samples))

model = Vits(config, ap, tokenizer, speaker_manager=None)
trainer = Trainer(TrainerArgs(), config, OUT, model=model,
                  train_samples=train_samples, eval_samples=eval_samples)
trainer.fit()

import glob, IPython.display as ipd
from TTS.utils.synthesizer import Synthesizer

run_dir = sorted(glob.glob(f'{OUT}/vits_sinhala*'))[-1]
ckpt = f'{run_dir}/best_model.pth'
cfg  = f'{run_dir}/config.json'
print('Using', ckpt)

syn = Synthesizer(tts_checkpoint=ckpt, tts_config_path=cfg, use_cuda=True)
text = 'මේ හෝටලයේ ඉඳන් දුම්රිය ස්ථානයට යන්න පුළුවන් ලේසිම සහ වේගවත්ම පාර මොකක්ද කියලා මට කියන්න පුළුවන්ද?'   # 'Good morning!'
wav = syn.tts(text)
syn.save_wav(wav, '/content/out.wav')
ipd.Audio('/content/out.wav')

import shutil, glob, os
from google.colab import drive
drive.mount('/content/drive')

src = sorted(glob.glob('/content/vits_si_out/vits_sinhala*'))[-1]
dst = '/content/drive/MyDrive/vits_si_backup'
os.makedirs(dst, exist_ok=True)

for f in ['best_model.pth', 'config.json']:
    p = os.path.join(src, f)
    if os.path.exists(p):
        shutil.copy(p, dst); print('saved', f)

ckpts = sorted(glob.glob(f'{src}/checkpoint_*.pth'),
               key=lambda x: int(x.split('_')[-1].split('.')[0]))
if ckpts:
    shutil.copy(ckpts[-1], dst); print('saved', os.path.basename(ckpts[-1]))

print('Drive backup contents:', os.listdir(dst))